#!/bin/bash


if ! [ "${MAIL_RELAY_HOST}" = "" ]; then
    sed -i "s/relayhost =.*/relayhost = ${MAIL_RELAY_HOST}/" /etc/postfix/main.cf
fi
if ! [ "${MAIL_INET_PROTOCOLS}" = "" ]; then 
    sed -i "s/inet_protocols =.*/inet_protocols = ${MAIL_INET_PROTOCOLS}/" /etc/postfix/main.cf
fi
sed -i "s/myhostname =.*/myhostname = $(hostname)/" /etc/postfix/main.cf
sed -i "s/mydestination =.*/mydestination = ${NAGIOS_FQDN}, \$myhostname, localhost.localdomain, localhost/" /etc/postfix/main.cf
sed -i "s/smtp_sasl_auth_enable =.*/smtp_sasl_auth_enable = yes/" /etc/postfix/main.cf
sed -i "s/smtp_sasl_security_options =.*/smtp_sasl_security_options = noanonymous/" /etc/postfix/main.cf
sed -i "s/smtp_sasl_password_maps =.*/smtp_sasl_password_maps = hash:\/etc\/postfix\/sasl_passwd/" /etc/postfix/main.cf
sed -i "s/smtp_use_tls =.*/smtp_use_tls = yes/" /etc/postfix/main.cf
sed -i "s/smtp_tls_CAfile =.*/smtp_tls_CAfile = \/etc\/ssl\/certs\/ca-certificates.crt/" /etc/postfix/main.cf
sed -i "s/virtual_alias_domains =.*/virtual_alias_domains = $(hostname)/" /etc/postfix/main.cf
sed -i "s/virtual_alias_maps =.*/virtual_alias_maps = hash:\etc\postfix\/virtual/" /etc/postfix/main.cf

sed -i "/^myorigin =.*/d" /etc/postfix/main.cf
echo "${NAGIOS_FQDN}" > /etc/mailname

echo "${MAIL_RELAY_HOST} ${GUSER}:${GPASS}" > /etc/postfix/sasl_passwd
postmap /etc/postfix/sasl/sasl_passwd

#postfix runs in a chroot and needs resolv.conf to resolve hostnames
cp /etc/resolv.conf /var/spool/postfix/etc/resolv.conf

exec /usr/lib/postfix/sbin/master -d -c /etc/postfix
