version: '2'
volumes:
    resin-data:
    nagiosetc2347:
    nagiosvar:
    customplugins:
    nagiosgraphvar:
    nagiosgraphetc:
services:
  node-red:
    build: ./node-red
    volumes:
      - 'resin-data:/data'
    restart: always
    privileged: true
    labels:
      io.balena.features.supervisor-api: '1'
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/mem:/dev/mem"
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/i2c-1:/dev/i2c-1"
      - "/dev/video0:/dev/video0"
      - "/dev/video1:/dev/video1"
    network_mode: host
    ports:
      - 80:80
  rtl-amr:
    build: ./rtl-amr
    devices:
      - '/dev:/dev'
    restart: always
    privileged: true
    network_mode: host
    ports:
      - 1234:1234
  mqtt:
    build: ./mqtt
    container_name: mqtt
    restart: unless-stopped
    network_mode: host
    ports:
      - 1883:1883
      - 9001:9001
      - 8883:8883
  nagios:
    build: ./nagios
    container_name: nagios
    restart: unless-stopped
    ports:
    - 8888:80
    volumes:
    - nagiosetc2347:/opt/nagios/etc
    - nagiosvar:/opt/nagios/var
    - customplugins:/opt/Custom-Nagios-Plugins
    - nagiosgraphvar:/opt/nagiosgraph/var
    - nagiosgraphetc:/opt/nagiosgraph/etc
