version: '2'
volumes:
    resin-data:
services:
  node-red:
    build: ./node-red
    volumes:
      - 'resin-data:/data'
    restart: always
    privileged: true
    network_mode: host
    labels:
      io.balena.features.supervisor-api: '1'
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/mem:/dev/mem"
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/i2c-1:/dev/i2c-1"
      - "/dev/video0:/dev/video0"
      - "/dev/video1:/dev/video1"
    ports:
      - 80:80
  rtl-amr:
    build: ./rtl-amr
    devices:
      - '/dev/bus/usb:/dev/bus/usb'
    restart: always
    privileged: true
    network_mode: host
    ports:
      - 1234:1234
  mqtt:
    build: ./mqtt
    network_mode: host
    container_name: mqtt
    ports:
      - 1883:1883
      - 9001:9001
    restart: unless-stopped
  mysql:
    image: hypriot/rpi-mysql
    ports:
      - 3306:3306
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: Fc3qPNwyGJxPtQsX3585
